name: Deploy to Dev

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Passcode'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploying to Dev
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DEV_IP }}
          username: ${{ secrets.DEV_USER }}
          password: ${{ secrets.DEV_PASS }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            cd /var/www/ilovejson.com/
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/git_rsa
            git checkout .
            git pull
            npm ci
            NODE_OPTIONS="--max-old-space-size=4096" npm run build
            pm2 reload ilovejson --update-env
          debug: true
